Zhilfond.UI/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Interfaces;
using DAL.Repositories;

namespace UI.Controllers
{
    public class MainController : Controller
    {
        static readonly IUsersRepository _repository = new UsersRepository();

        //
        // GET: /Main/

        public ActionResult Index()
        {
            var o = HttpContext.Session["token"];
            if (o != null)
            {
                return View();
            }
            return RedirectToAction("Index", "AccessDenied");
        }

        public ActionResult Constructor()
        {
            var o = HttpContext.Session["token"];
            if (o != null)
            {
                DAL.Models.UserV u = _repository.GetVByToken(o.ToString());
                if (u.Role == "Администраторы")
                    return View();
            }
            return RedirectToAction("Index", "AccessDenied");
        }

        public ActionResult Dicts()
        {
            var o = HttpContext.Session["token"];
            if (o != null)
            {
                DAL.Models.UserV u = _repository.GetVByToken(o.ToString());
                if (u.Role == "Администраторы")
                    return View();
            }
            return RedirectToAction("Index", "AccessDenied");
        }

        public ActionResult Settings()
        {
            var o = HttpContext.Session["token"];
            if (o != null)
            {
                DAL.Models.UserV u = _repository.GetVByToken(o.ToString());
                if (u.Role == "Администраторы")
                    return View();
            }
            return RedirectToAction("Index", "AccessDenied");
        }
    }
}

Zhilfond.UI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Http;
using System.Net.Http;
using System.Net;
using UI.Filters;
using DAL.Interfaces;
using DAL.Repositories;

namespace UI.Controllers
{
    public class UsersController : Controller
    {
        static readonly IUsersRepository _repository = new UsersRepository();

        public ActionResult Index()
        {
            var o = HttpContext.Session["token"];
            if (o != null)
            {
                DAL.Models.UserV u = _repository.GetVByToken(o.ToString());
                if (u.Role == "Администраторы")
                    return View();
            }
            return RedirectToAction("Index", "AccessDenied");
        }

        public ActionResult ChangePassword()
        {
            var o = HttpContext.Session["token"];
            if (o != null)
            {
               return View();
            }
            return RedirectToAction("Index", "AccessDenied");
        }

        public ActionResult Logoff()
        {
            System.Web.HttpContext.Current.Session["token"] = null;
            return this.RedirectToAction("Index","Home");
        }
    }
}

Zhilfond.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
        <div class="modal"></div>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">Система управления жилищным фондом</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="top_menu" style="display:none">
                           <li class="top_menu_item_all"  style="display:none">@Html.ActionLink("Главная", "Index", "Main")</li> 
                           <li class="top_menu_item_admin"  style="display:none">@Html.ActionLink("Пользователи", "Index", "Users")</li>                          
                           <li class="top_menu_item_all"  style="display:none">@Html.ActionLink("Сменить пароль", "ChangePassword", "Users")</li>
                           <li class="top_menu_item_admin"  style="display:none">@Html.ActionLink("Справочники", "Dicts", "Main")</li>
                           <li class="top_menu_item_admin"  style="display:none">@Html.ActionLink("Конструктор", "Constructor", "Main")</li>
                           <li class="top_menu_item_admin"  style="display:none">@Html.ActionLink("Настройки", "Settings", "Main")</li>
                           <li class="top_menu_item_all"  style="display:none">@Html.ActionLink("Выход", "Logoff", "Users")</li>
                        </ul>
                    </nav> 
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Жилфонд</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        
    
<script src="~/Scripts/jquery-1.9.1.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.10.3.js" type="text/javascript"></script>
<script src="~/Scripts/i18n/grid.locale-en.js" type="text/javascript"></script>
<script src="~/Scripts/carhartl/jquery.cookie.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.splitter-0.12.0.js"></script>
<script src="~/Scripts/global.js"></script>
<script src="~/Scripts/ajaxfileupload.js"></script>
<script src="~/Scripts/jshashtable-3.0.js"></script>
<script src="~/Scripts/fileupload/js/vendor/jquery.ui.widget.js"></script>
<script src="~/Scripts/fileupload/js/jquery.iframe-transport.js"></script>
<script src="~/Scripts/fileupload/js/jquery.fileupload.js"></script>
<script src="~/Scripts/crypto-js/rollups/sha256.js"></script>
<script src="~/Scripts/crypto-js/rollups/aes.js" type="text/javascript"></script>

<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/ext/jsbn.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/ext/jsbn2.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/ext/rsa.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/ext/rsa2.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/ext/base64.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/rsapem-1.1.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/rsasign-1.2.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/asn1hex-1.1.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/x509-1.1.js"></script>
<script type="text/javascript" src="~/Scripts/jsrsasign-4.2.1/crypto-1.1.js"></script>



        <script>  
            $(document).ready(function () {
             $body = $("body");

             $(document).on({
                 ajaxStart: function () {
                     $body.addClass("loading");
                 },
                 ajaxStop: function () {
                     $body.removeClass("loading");
                 }
             });

             $("#top_menu").menu();
          });
        </script>

        <style>
            #top_menu
            {
                border:0px;
            }

            #top_menu > li 
            { 
                float: left;
                display: block;
                width: auto !important;
            }

             .ui-menu-item a 
             {
                font-size: 0.9em;
             }     

        </style>

        @RenderSection("scripts", required: false)
    </body>
</html>